[program:tailscaled]
command=/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --tun=userspace-networking --socks5-server=localhost:1055
autostart=true
autorestart=true
stdout_logfile=/var/log/tailscaled.log
stderr_logfile=/var/log/tailscaled.err
priority=100
